# Header
menu:
  Home: /
  Archives: /archives

# URL basename of the main cover image. Make sure you deliver three files:
# <index_cover>@preview.gif, <index_cover>.jpg (1920 px wide)
# and <index_cover>@2x.jpg (3840 px wide).
index_cover: /img/the-path

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: tomek-wiszniewski-cc
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/tomekwi_
github_url: https://github.com/tomekwi
